### ISSUE TITLE
Comcast Steam CDN

### ISSUE THREAD

**Issue by ndonaldson88** [uklans/cache-domains#106]
Noticed that Comcast has dedicated steam CDN servers using the following domain names:

steam-dns.top.comcast.net
steam-dns-2.top.comcast.net

**Comment by unspec** [comment]
The new steam lancache system should hopefully aleviate the need to deal with ISP specific CDN nodes:
https://github.com/uklans/cache-domains/pull/124

Further reading:
https://github.com/lancachenet/monolithic/issues/85
https://store.steampowered.com/news/57829/
