### ISSUE TITLE
additional steam domain?

### ISSUE THREAD

**Issue by MK-42** [uklans/cache-domains#108]
### Describe the issue you are having
had non-cached traffic with content-paths indicating steam-client downloads to media4.steampowered.com

### Describe your setup?
steamcache/generic with custom set dns redirects through windows-server

### Are you running sniproxy
yes

seems like that subdomain is specifically used for steam client downloads from a short google-survey. It might be valid to cache it.

**Comment by MathewBurnett** [comment]
It hard to be sure what media4.steampowered.com contains. I would have expected that it has images and video content in it.

**Comment by MathewBurnett** [comment]
Steams new lancache.steamcontent.com feature should now mean we are catching all the cdn's that they intend to be for bulk content.
