### ISSUE TITLE
How to use hostnames files

### ISSUE THREAD

**Issue by dsozzi** [uklans/cache-domains#13]
Hi, sorry for the noobish question but how should I use those files? Should I simply get a game provider dns list (steam.txt for example) and add each key to my central LAN router or there is an alternative method to add them all at once to my router configuration?

thanks

**Comment by Lepidopterist** [comment]
Hey,

It very much depends on the router unfortunately, so specific instructions are difficult to give.  However, the premise is correct - you'll need to point each of the hostnames in each file you choose to use, to a single IP address hosting the cache.

**Comment by dsozzi** [comment]
Ok that's great thx
