### ISSUE TITLE
Steam no longer cache through public ip

### ISSUE THREAD

**Issue by manafoo** [uklans/cache-domains#135]
.Sorry for the short topic I'm using a phone.
Steam does not cache content if you are using public ips on your caching machine anymore  "used to work" so you need to assign local ip address example 192.168.1.x in order for it to work

**Comment by unspec** [comment]
Yes, that is correct. I'm not quite sure why the new issue?

**Comment by manafoo** [comment]
> Yes, that is correct. I'm not quite sure why the new issue?

Because it's a security measure done by the game providers steam one of them. To prevent attacks i guess so in thwir programming they don't switch to http instead of https if they don't see a local ip

**Comment by unspec** [comment]
Yes, i just dont know why you opened a new issue? We discussed this in the #98 already?

**Comment by manafoo** [comment]
> Yes, i just dont know why you opened a new issue? We discussed this in the #98 already?

I apologize i wasn't aware that there was one. You can delete this one

**Comment by unspec** [comment]
This is expected behaviour from steam, and there is nothing that this project can do about it (nor do we particularly see this a problem or something that needs to be changed).

I'm going to close this issue as cantfix. If there is a specific thing to be discussed feel free to reopen.
