### ISSUE TITLE
please add to apple update cache 

### ISSUE THREAD

**Issue by erdenebayar8291** [uklans/cache-domains#147]
### DNS Configuration
```
<!-- Paste either your docker run command for the DNS container OR explain how you have setup DNS zone files etc -->
```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
<!-- If you are running sniproxy paste the output to the following command
docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c
-->
```

**Comment by MathewBurnett** [comment]
apple doesn't have http caching of content and has its own mechanism see #132 for detail
