### ISSUE TITLE
[Question] Add pypi.org and Fedora Linux RPM updates

### ISSUE THREAD

**Issue by robertpro** [uklans/cache-domains#148]
### Describe the issue you are having
Is is possible for me to add not game related content? I am interested on caching Docker images, Fedora Linux RPMs and Python packages, since we are developers, we usually need to download the same content every docker build, tox tests, etc.

I know there are other solutions, like Lancache pointed out in the [FAQ -WSUS](https://lancache.net/docs/faq/#why-do-you-mention-you-support-windows-update-cant-we-use-wsus), 

### Describe your setup?
Undaid [lancache-bundle](https://github.com/Josh5/lancache-bundle)

### Are you running sniproxy
N/A

### DNS Configuration
N/A

### Sniproxy output
N/A

```

**Comment by riconnon** [comment]
Docker Hub and PyPI both serve their content via HTTPS so this would not be possible for those I believe
Fedora RPMs may be possible but it's pretty niche and not useful for "most LANgoers"

There would be nothing stopping you running a lancache pointed at a fork of this repo, or in fact any other repo with the same structure though.

**Comment by robertpro** [comment]
Thanks for the fast response, I was thinking about forking the repo in order to adjust lancache to my needs, thank you!
