### ISSUE TITLE
Steam Cloudflare CDN

### ISSUE THREAD

**Issue by RedSpid3r** [uklans/cache-domains#152]
Didn't spot this one in the domain list, but it seems steam is using `cdn.cloudflare.steamstatic.com` for a lot of their store page content as well as user avatars etc.

```
https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg?t=1607428743
https://cdn.cloudflare.steamstatic.com/steamcommunity/public/images/avatars/d5/d52743ced29f850a32112bf611c2120b38fc7c5d.jpg
```

**Comment by MathewBurnett** [comment]
We don't cache the store content. Also both the links you mentioned are https which will not cache
