### ISSUE TITLE
Blizzard game cache not works

### ISSUE THREAD

**Issue by yangcaixing** [uklans/cache-domains#153]
Describe the issue you are having
When download Blizzard games, the traffic go through from local internet, not via lancache server, I already add the DNS items forward to lancache, but I find when I download blizzard game, it access to this DNS site "http://client05.pdl.wow.battlenet.com.cn/tpr/hs/data/1c/d3/1cd31f51f8d03125f1f19705a5346141", it not include in Lancache-DNS, How can I add it to Lancache-DNS ,thanks very much.

How are you running the container(s)
docker-compose up -d

version: '2'
services:
dns:
image: lancachenet/lancache-dns:latest
env_file: .env

restart: unless-stopped
ports:
  - ${DNS_BIND_IP}:53:53/udp
  - ${DNS_BIND_IP}:53:53/tcp
HTTPS requests are now handled in monolithic directly
you could choose to return to sniproxy if desired
sniproxy:
image: lancachenet/sniproxy:latest
env_file: .env
restart: unless-stopped
ports:
- 443:443/tcp
monolithic:
image: lancachenet/monolithic:latest
env_file: .env

restart: unless-stopped
ports:
  - 80:80/tcp
  - 443:443/tcp
volumes:
  - ${CACHE_ROOT}/cache:/data/cache
  - ${CACHE_ROOT}/logs:/data/logs
DNS Configuration
USE_GENERIC_CACHE=true

IP addresses that the lancache monolithic instance is reachable on
Specify one or more IPs, space separated - these will be used when resolving DNS hostnames through lancachenet-dns. Multiple IPs can improve cache priming performance for some services (e.g. Steam)
Note: This setting only affects DNS, monolithic and sniproxy will still bind to all IPs by default
LANCACHE_IP=172.20.90.247

IP address on the host that the DNS server should bind to
DNS_BIND_IP=172.20.90.247

DNS Resolution for forwarded DNS lookups
UPSTREAM_DNS=114.114.114.114

In windows DNS server, Add steam/blizzard condition forward to Lancache-DNS.

Output of container(s)

[blizzard] 172.20.60.52 / - - - [05/Jan/2021:09:34:15 +0000] "GET /geoip HTTP/1.1" 204 0 "-" "Bootstrapper/1.17.1.3061" "MISS" "nydus.battle.net" "-"
[blizzard] 172.20.60.52 / - - - [05/Jan/2021:09:40:19 +0000] "GET /geoip HTTP/1.1" 204 0 "-" "Bootstrapper/1.17.1.3061" "MISS" "nydus.battle.net" "-"
[blizzard] 172.20.60.52 / - - - [05/Jan/2021:10:08:27 +0000] "GET /geoip HTTP/1.1" 204 0 "-" "Bootstrapper/1.17.1.3061" "MISS" "nydus.battle.net" "-"

**Comment by SkylineLeo** [comment]
I have this problem too

**Comment by MathewBurnett** [comment]
see PR #154 

you can add a domain and use your own forked repo for regional differences

**Comment by yangcaixing** [comment]
> see PR #154
> 
> you can add a domain and use your own forked repo for regional differences

Thanks Proto, it works now.

**Comment by yangcaixing** [comment]
Hi Proto, 
   I use "docker run xxx" command still have some issue, it cause steam/epic/blizzard all not works,  it seems lancache don't proxy traffic, so cannot download or access game , but when use "docker-compose up -d" command, steam/epic works fine, could please help check, or if my command have some errors, thanks.

docker run --restart unless-stopped --name lancache-dns --detach -p 172.20.90.248:53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=172.20.90.248 -e DNS_BIND_IP=172.20.90.248 -e UPSTREAM_DNS="114.114.114.114" -e CACHE_DOMAINS_REPO="https://github.com/yangcaixing/cache-domains.git" lancachenet/lancache-dns:latest

docker run --restart unless-stopped --name lancache --detach -v /cache/data:/data/cache -v /cache/logs:/data/logs -p 172.20.90.248:80:80 -e CACHE_DOMAINS_REPO="https://github.com/yangcaixing/cache-domains.git" lancachenet/monolithic:latest

<img width="916" alt="1" src="https://user-images.githubusercontent.com/41502299/104544522-ed1fcc80-5662-11eb-833d-79bccccd6bdc.png">
