### ISSUE TITLE
create-unbound.sh seems not to respect wildcards ; creates duplicates

### ISSUE THREAD

**Issue by Joly0** [uklans/cache-domains#163]
### Describe the issue you are having
the create-unbound.sh file while using seems not to respect wildcard entries in the txt files for the domains (good examples are windowsupdates or steam). The entries with wildcards just get the wildcard removed and added to the output conf resulting in duplicate entries for those files.

### Describe your setup?
pihole with unbound letting unbound point to my lancache.

### Are you running sniproxy
no

### DNS Configuration
```
used the create-unbound.sh script
```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
none
```

**Comment by nightah** [comment]
What makes you believe that wildcards are not respected?

In Unbound configuration the below caters for both `windowsupdate.com` and `*.windowsupdate.com`.

```conf
  local-zone: "windowsupdate.com" redirect
  local-data: "windowsupdate.com 30 IN A 10.10.10.200"
```

You're not wrong about the duplicates but that should not cause any issues.

**Comment by Joly0** [comment]
Ahh, ok. Then its my bad, i misinterpreted the configs and thought it would kick out the wildcards.

Though its still adding duplicates to the files which might confuse people (like me), but yes, thats not really and issue, more like an inconvinience
