### ISSUE TITLE
Add Adobe, google and MS office?

### ISSUE THREAD

**Issue by yurividal** [uklans/cache-domains#192]
[This](https://github.com/tsvcathed/nginx_lancache)  project claims to be able to cache Microsoft, Chrome, Ms office and Adobe updates via DNS intercepting.
Any chance these can be added to lancache?
Would it be as simple as adding the domains to  txt file in this project?

**Comment by DragonQ** [comment]
Windows Updates are already included in the windowsupdates.txt config file. I tried to make an Office-only config file including just these lines a while back:
```
officecdn.microsoft.com
officecdn.microsoft.com.edgesuite.net
```
It worked for a few months but stopped working recently, not sure why. I don't want to use all Microsoft domains because I use WSUS for Windows updates, and I'd rather Windows updates didn't also clog my LANCache.

**Comment by VibroAxe** [comment]
> [This](https://github.com/tsvcathed/nginx_lancache) project claims to be able to cache Microsoft, Chrome, Ms office and Adobe updates via DNS intercepting. Any chance these can be added to lancache? Would it be as simple as adding the domains to txt file in this project?

Add a .txt and update the cache_domains.json. I'm pretty sure when we have looked at these in the past they exclusively use SSL for downloads, so whilst they go through that cache, they are probably being proxied vs SNI. If you could prove you get a bunch of cache hits though, would happily consider a PR.

**Comment by yurividal** [comment]
I have actually done this, and  ran on 2 of my LANs for over 2 months. I did get hits on Adobe and a few on google (google cached about 2Gigs over 2 months, though).
The office one seems to not do anything. I have screenshots from my elk stack that i use to minutos lancache, im happy to share those if you want.

**Comment by VibroAxe** [comment]
Brilliant, if you create a PR with these changes in, and the screen shots from the ELK stack, i'll gladly merge

**Comment by yurividal** [comment]
Here it is: (note, this was NOT a gaming LAN. This was deployed in a fairly big network, but mostly a work environment)
![image](https://user-images.githubusercontent.com/8555749/184320127-0a10ee5f-fdf7-4781-952a-9cf32e2b3c95.png)

**Comment by VibroAxe** [comment]
> Here it is: (note, this was NOT a gaming LAN. This was deployed in a fairly big network, but mostly a work environment) ![image](https://user-images.githubusercontent.com/8555749/184320127-0a10ee5f-fdf7-4781-952a-9cf32e2b3c95.png)

Interestingly on this, you have 102GB of "unknown" traffic, implies you've got a misconfiguration between your DNS and your lancache?

**Comment by yurividal** [comment]
i would have to investigate the logs to see what the unknown traffic is hitting. let me look into it.

**Comment by yurividal** [comment]
weird, most of the unknown upstream logs show access to this:
````
	
[192.168.34.42] 10.10.0.1 / 192.168.34.43 - - [12/Aug/2022:10:27:00 +0100] "GET / HTTP/1.0" 508 0 "-" "Go-http-client/1.1" "-" "192.168.34.42" "bytes=0-1048575
````

**Comment by GamerKingFaiz** [comment]
What's the program you're using to see the LanCache stats?

**Comment by yurividal** [comment]
> What's the program you're using to see the LanCache stats?

I am using logstash to parse the access logs and store the data in elasticsearch. Then i use grafana to visualize the elasticsearch data. 

There is an ELK example somewhere on github that has a pre-built logstash + elastic + kibana setup.
