### ISSUE TITLE
If will to support tiktok

### ISSUE THREAD

**Issue by Crazy-Young** [uklans/cache-domains#204]
There are a lot of tiktok application traffic in hotels or gyms.

**Comment by VibroAxe** [comment]
Tictok is SSL traffic so we can't mitm it in afraid. Unless they have changed and you can provide host names & traffic dump we won't be any to add this

**Comment by DodgeThisss** [comment]
Hello sorry to post on a closed issue, I've done a bit of investigation regarding tiktok.
The thing is my ISP has a Akamai Edge server or some sort of peering with akamai, most tiktok traffic is server via this akamai cdn at my isp's via the following domains: webapp-prime.tiktok.com and va.tiktokcdn.com also a lot of subdomains but those are the main ones.
When you request a video via the mobile app or browser it requests a HTTPS url to any of the domains above, if I intercept and replay the same url but with http not https I also get server the content that means http is possible.

How can we test via lancache ?

**Comment by DodgeThisss** [comment]
I'll work on that using something like sslstrip and feedback.
