### ISSUE TITLE
MSFS 2020 doesn't cache

### ISSUE THREAD

**Issue by askiiart** [uklans/cache-domains#234]
### Describe the issue you are having
LanCache does not cache MSFS 2020 downloads, aside from the initial launcher download in Steam.

### Describe your setup?
- Downloading MSFS 2020 on Windows 10 IoT Enterprise LTSC, with IPv4 disabled (otherwise it does IPv6 lookups, bypassing the DNS overrides)
- Running LanCache monolithic and DNS in Docker on another server.
- LanCache DNS's upstream DNS is my OPNsense router, which then has Mullvad DoT DNS set as its upstream.

### Are you running sniproxy
No.

### DNS Configuration
DNS is set up via the LanCache DNS container.

### Sniproxy output
N/A

### More info
I was unable to intercept it with HTTP Toolkit because MSFS says the certificate is invalid, despite installing the certificate on the machine.

**Comment by mintopia** [comment]
Unfortunately MSFS fetches content from CDNs using TLS/HTTPS. This means Lancache is unable to cache it unfortunately.

**Comment by askiiart** [comment]
> Unfortunately MSFS fetches content from CDNs using TLS/HTTPS. This means Lancache is unable to cache it unfortunately.

Ah alright, thank you.

**Comment by askiiart** [comment]
Just wondering: The download servers seem to have HSTS enabled, since it doesn't work with HTTP Toolkit's MITM-ing. But for *theoretical non-HSTS* HTTPS servers, if the cache had HTTPS with a self-signed cert, and I added that cert to the local machine, then wouldn't it be able to cache downloads from the theoretical non-HSTS HTTPS server?

**Comment by mintopia** [comment]
Yes, if you installed a certificate on your PC that would work - however it's not something we recommend or encourage.

In a LAN party environment, if I was asked to install a certificate on my PC by the organisers, I'd refuse to do it.
