### ISSUE TITLE
Generating AdGuard Config let it still be necessary to let a DNS server for LANCache running

### ISSUE THREAD

**Issue by Hornochs** [uklans/cache-domains#235]
### Describe the issue you are having
Script generator for AdGuard generates the wrong modus

### Describe your setup?
AdGuard directly and later LANCache in docker.
—————
Hey Guys,

I noticed today that the script of generating the AdGuard Config makes it still necessary to let the DNS Server from LANCache be Running. But my goal is to let only one DNS server run. Which means the script shouldn’t generate specific upstream DNS, rather it should generate DNS rewrites that points directly to the LANCache. In that way there won’t be another instance of an DNS server needed.

**Comment by Hornochs** [comment]
I’ll try to build a bash script which generates the needed YAML output. It’s working what I did manually

**Comment by nightah** [comment]
Not sure I understand your description of the problem, the whole point of the script generation is so that your upstream DNS service such as AdGuard can be called directly and the LANCache DNS container isn't necessary anymore.

**Comment by Hornochs** [comment]
And there is the Problem.

The script generates a config, which tells Adguard to use a different Upstream DNS server on the LANcache domains. It is not an DNS Rewrite. Which means that in the current state the LANCache DNS Container is still necessary.


Am 19.03.2024 um 01:53 schrieb Amir Zarrinkafsh - notifications at github.com ***@***.***>:

﻿

Not sure I understand your description of the problem, the whole point of the script generation is so that your upstream DNS service such as AdGuard can be called directly and the LANCache DNS container isn't necessary anymore.

**Comment by nightah** [comment]
The intent of the scripts in this repository are to create DNS rules to point to your LANcache instance. Not to forward to another upstream DNS on a per domain basis.

The easier way to achieve this with AdGuard would be to set its singular upstream as LANCache DNS and then set that upstream to whatever you use to resolve external DNS.

**Comment by Hornochs** [comment]
That’s what I‘m doing atm. My AdGuard has the dns rewrites which points to the LANCache without the DNS container. And a upstream DNS Server is set for the other queries. I‘ll have a look in our git repo in some days the give you a sample config.

Unterwegs gesendet
.

**Comment by martincaddick** [comment]
Not a perfect solution but works for me. I just went to the Custom Filtering Rules and added the IP<space>hostname like this

192.168.2.2 com.edgesuite.net
192.168.2.2 com.nsatc.net
192.168.2.2 download.windowsupdate.com
-- snip --

**Comment by shinji257** [comment]
I edited the AdGuardHome.yaml file directly to bulk add Adguard Home rewrites for all the new DNS entries.  This way at least the log records in an expected way.  I manually handle it from there based on new git commits here.

Example:
```yaml
  rewrites:
    - domain: assetcdn.101.arenanetworks.com
      answer: 10.0.0.209
    - domain: assetcdn.102.arenanetworks.com
      answer: 10.0.0.209
    - domain: assetcdn.103.arenanetworks.com
      answer: 10.0.0.209
```
