### ISSUE TITLE
More cdn's for sony.

### ISSUE THREAD

**Issue by nexusofdoom** [uklans/cache-domains#30]
ref url 
http://www.psdevwiki.com/ps4/PKG_files/rawlist1

ic.ae179e00.11a2c5.gs2.sonycoment.loris-e.llnwd.net

**Comment by JasonRivers** [comment]
Thanks for this. We are looking at how greedy we can be with wildcards on the domain before we make the change to include this.

**Comment by VibroAxe** [comment]
@JasonRivers did we get anywhere with looking at this?

**Comment by VibroAxe** [comment]
From #53 

```
local-zone: "pls.patch.station.sony.com." redirect local-data: "pls.patch.station.sony.com. 30 IN A YOUR-IP-ADDRESS" local-zone: "playstation.net." transparent local-zone: "gs2.ww.prod.dl.playstation.net." redirect local-data: "gs2.ww.prod.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS" local-zone: "gs2.sonycoment.loris-e.llnwd.net." redirect local-data: "gs2.sonycoment.loris-e.llnwd.net. 30 IN A YOUR-IP-ADDRESS" local-zone: "theia.dl.playstation.net." redirect local-data: "theia.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS" local-zone: "tmdb.np.dl.playstation.net." redirect local-data: "tmdb.np.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS" local-zone: "gs-sec.ww.np.dl.playstation.net." redirect local-data: "gs-sec.ww.np.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS" local-zone: "playstation4.sony.akadns.net." redirect local-data: "playstation4.sony.akadns.net. 30 IN A YOUR-IP-ADDRESS" local-zone: "gs2-ww-prod.psn.akadns.net." redirect local-data: "gs2-ww-prod.psn.akadns.net. 30 IN A YOUR-IP-ADDRESS" local-zone: "gs2.ww.prod.dl.playstation.net.edgesuite.net." redirect local-data: "gs2.ww.prod.dl.playstation.net.edgesuite.net. 30 IN A YOUR-IP-ADDRESS" local-zone: ".cloudfront.net." redirect local-data: ".cloudfront.net. 30 IN A YOUR-IP-ADDRESS" local-zone: ".deploy.static.akamaitechnologies.com." redirect local-data: ".deploy.static.akamaitechnologies.com. 30 IN A YOUR-IP-ADDRESS" local-zone: ".llnw.net." redirect local-data: ".llnw.net. 30 IN A YOUR-IP-ADDRESS"
```

Note: At least some of these additional domains are inadvisable due to being to high a catchall (see cloudfront.net)

**Comment by some-username-here1** [comment]
`*.deploy.static.akamaitechnologies.com` most likely isn't a possible addition since that's also being used by Xbox Live and Nintendo eShop

**Comment by unspec** [comment]
Still needs a review of the linked wiki and any useful additions adding to a PR

**Comment by unspec** [comment]
Looking over this we have the following from the wiki page:
gs2.ww.prod.dl.playstation.net
ic.ae179e00.05f0ff.gs2.sonycoment.loris-e.llnwd.net
ic.ae179e00.11a2c5.gs2.sonycoment.loris-e.llnwd.net

And the following from the submission to the other project:
pls.patch.station.sony.com 
gs2.ww.prod.dl.playstation.net 
gs2.sonycoment.loris-e.llnwd.net
theia.dl.playstation.net 
tmdb.np.dl.playstation.net 
gs-sec.ww.np.dl.playstation.net 
playstation4.sony.akadns.net 
gs2-ww-prod.psn.akadns.net 
gs2.ww.prod.dl.playstation.net.edgesuite.net 

(Duplicates and obvious bad ideas removed)

Of that list, these are already in our repo:
pls.patch.station.sony.com 
gs2.ww.prod.dl.playstation.net

As is: gs2.sonycoment.loris-e.llnwd.net, however it looks like there are multiple subdomains, so *.gs2.sonycoment.loris-e.llnwd.net is likely sensible to add and probably *.gs2.ww.prod.dl.playstation.net as well.

Next, based on the gs2 naming scheme, the following (with their wildcard versions) seem sensible too:
gs2-ww-prod.psn.akadns.net 
gs2.ww.prod.dl.playstation.net.edgesuite.net

Seems sensible to add this one too:
playstation4.sony.akadns.net

Finally there are a bunch more on *.dl.playstation.net:
theia.dl.playstation.net 
tmdb.np.dl.playstation.net 
gs-sec.ww.np.dl.playstation.net

It could be worth just caching *.dl.playstation.net, however there is no way to tell what none cachable type content they may serve from that domain.

Therefore i'd suggested the list should be either:

pls.patch.station.sony.com
gs2.ww.prod.dl.playstation.net
*.gs2.ww.prod.dl.playstation.net
gs2.sonycoment.loris-e.llnwd.net
*.gs2.sonycoment.loris-e.llnwd.net
gs2-ww-prod.psn.akadns.net
*.gs2-ww-prod.psn.akadns.net
gs2.ww.prod.dl.playstation.net.edgesuite.net
*.gs2.ww.prod.dl.playstation.net.edgesuite.net
playstation4.sony.akadns.net
theia.dl.playstation.net 
tmdb.np.dl.playstation.net 
gs-sec.ww.np.dl.playstation.net

OR

pls.patch.station.sony.com
dl.playstation.net
*.dl.playstation.net
gs2.sonycoment.loris-e.llnwd.net
*.gs2.sonycoment.loris-e.llnwd.net
gs2-ww-prod.psn.akadns.net
*.gs2-ww-prod.psn.akadns.net
gs2.ww.prod.dl.playstation.net.edgesuite.net
*.gs2.ww.prod.dl.playstation.net.edgesuite.net
playstation4.sony.akadns.net

Dependant on how adverterous we feel.

Anyone with a PS4 want to do some further testing?

**Comment by ThomasRunting** [comment]
Id love to see this merged. I had my ps4 use my lancache and then stop. But it went strait to here

`ic.9e8cd500.101e5b.gs2.sonycoment.loris-e.llnwd.net`

**Comment by ThomasRunting** [comment]
forked the repo and added 
```
pls.patch.station.sony.com
gs2.ww.prod.dl.playstation.net
*.gs2.ww.prod.dl.playstation.net
gs2.sonycoment.loris-e.llnwd.net
*.gs2.sonycoment.loris-e.llnwd.net
gs2-ww-prod.psn.akadns.net
*.gs2-ww-prod.psn.akadns.net
gs2.ww.prod.dl.playstation.net.edgesuite.net
*.gs2.ww.prod.dl.playstation.net.edgesuite.net
playstation4.sony.akadns.net
theia.dl.playstation.net
tmdb.np.dl.playstation.net
gs-sec.ww.np.dl.playstation.net
```

Seems to be working properly now

**Comment by mintopia** [comment]
Domains added and merged in https://github.com/uklans/cache-domains/pull/167.

Thanks for the help with this one!
