### ISSUE TITLE
Windows 10 - unable to connect to update service

### ISSUE THREAD

**Issue by andyle2k** [uklans/cache-domains#39]
When using the domains from here via steamcache-dns Windows 10 is no longer able to connect to update service.

Windows 7 confirms to be working.

This started happening around a week ago (15 Oct 2018).

Thanks.

**Comment by VibroAxe** [comment]
Hi Andy

As per the issue template we need to know the answers to the following questions before we start looking into this:

### Describe your setup?
```<!-- What is your dns server, are you using steamcache/dns or another resolver, which cache proxy are you using -->```

### Are you running sniproxy
```<!-- Yes/no -->```

### DNS Configuration
```
<!-- Paste either your docker run command for the DNS container OR explain how you have setup DNS zone files etc -->
```

**Comment by andyle2k** [comment]
Hi,

Apologies. 

Describe your setup?

My DNS setup is via steamcache-dns. And the cache proxy I'm using is the steamcache-generic with the DNS setup for WSUSCACHE. 

Are you running sniproxy? No I am not. I've tried it with sniproxy and it didn't work either. So I don't think HTTPS is the problem. Also Windows 7 updates works just fine so I'm guessing Windows 10 is hitting some other CDN or server but is not able to redirect or resolve via steamcache-dns. 

DNS Configuration

I let steamcache-dns do all this. Looking at their script they're pulling the domain hostnames from here and putting it into their DNS database. 

Thanks.

**Comment by VibroAxe** [comment]
I'm pretty sure that wsus requires sniproxy since recent times. Can you reenable the sniproxy instance, reboot and then if you still get the connection error please give us the output of the following command:
`docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | grep microsoft | sort | uniq -c`

**Comment by andyle2k** [comment]
Would you believe me if I said the problem fixed itself overnight?

Well first I took your advice and installed sniproxy. It worked! I came back here and started typing my thank you note but... (with sniproxy installed) after reboots my docker containers all got stuck in a restart loop, with sniproxy stopped or removed there isn't this problem. Strange! 

So I removed sniproxy and tried updating from my Win10 VM and it works without it. So I'm still at a loss.

1) I know everything has been working fine up until last week
2) I know for sure that Windows 7 updates works fine during this past week whereas Windows 10 didn't

So I'm starting to think it might have an intermittent issue somewhere (not my ISP DNS because I tried using ISP as well as Google for upstream).

Anyway thank you very much for your time and effort. I might keep this open for a couple days just to check and determine whether anything else is wrong.

**Comment by VibroAxe** [comment]
I'd highly recommend reinstalling sniproxy, it's now required as part of the lancache infrastructure for a large number of CDN's we recommend always running it even as a "just in case"

**Comment by JasonRivers** [comment]
Just a note - I have seen issues with Windows 10 going through the cache, but thus far I haven't been able to narrow down exactly why, Mostly because work commitments have been keeping me too busy currently. if you're using the steamcache-dns for your DNS I currently recommend setting the environment "DISABLE_WSUS=true" until we can work out exactly what is causing the issue.

**Comment by VibroAxe** [comment]
might be worth something on the steamcache repo noting this is a know issue and to disable wsus for the moment?

**Comment by VibroAxe** [comment]
Leaving this here for future me

All windows update URLS:
```
http://windowsupdate.microsoft.com
http://*.windowsupdate.microsoft.com
https://*.windowsupdate.microsoft.com
http://*.update.microsoft.com
https://*.update.microsoft.com
http://*.windowsupdate.com
http://download.windowsupdate.com
http://download.microsoft.com
http://*.download.windowsupdate.com
http://wustat.windows.com
http://ntservicepack.microsoft.com
https://*.ws.microsoft.com
http://*.ws.microsoft.com
```

Only 80 & 443

**Comment by VibroAxe** [comment]
@JasonRivers so running the latest cachedomains and wccp intercept windows update seemed to work fine at stratlan. Thinking this might be a sniproxy issue somewhere
