### ISSUE TITLE
Steam may be using HTTPS for CDN

### ISSUE THREAD

**Issue by shinji257** [uklans/cache-domains#40]
Checking SNIProxy logs I found it was connecting to steamcdn-a.akamaihd.net via https.  Also I'm not getting any logging on steamcache anymore and checking local PC shows it connecting to 443 which means that it is getting pushed through sniproxy onto the actual server (no actual caching).  Sniproxy log shows 662 hits for steamcdn-a.akamaihd.net below.

### Describe your setup?
Using steamcache dns setup as primary dns on the network, using steamcache generic servers

### Are you running sniproxy
Yes

### DNS Configuration
Using portainer for management.
ENV:
UPSTREAM_DNS | 192.168.1.1
STEAMCACHE_IP | 192.168.1.221
ORIGINCACHE_IP | 192.168.1.222
BLIZZARDCACHE_IP | 192.168.1.223
STEAMCACHE_DNS_VERSION | 1
UPLAYCACHE_IP | 192.168.1.224

### Sniproxy output
     28 jdnowweb-s.cdn.ubi.com
    123 nydus.battle.net
     35 origin-a.akamaihd.net
  15412 river.data.ea.com
     41 static2.cdn.ubi.com
      8 static3.cdn.ubi.com
     24 static8.cdn.ubi.com
    662 steamcdn-a.akamaihd.net
      4 uat-ubiservices.cdn.ubi.com
     19 ubiservices.cdn.ubi.com
      2 valve300.steamcontent.com

**Comment by VibroAxe** [comment]
We are aware that steam is a mixed content engine now. Running the SniProxy is the correct resolution to this, unfortunately there is no way at present to enable us to cache anything which is transferred over https. 

Can you clarify if you think the logging on your steamcache is broken, or if you think that you are no longer seeing any traffic at all to the steam cache? We usually see a mix of traffic on steam hitting both the cache and the sniproxy

**Comment by sirsquidness** [comment]
You should experiment with rejecting the https CDN hostnames in sniproxy. Steam should then try other CDN sources, hopefully trying a plain text http one instead. I don't get any https sources here, so I can't test easily.

**Comment by VibroAxe** [comment]
@sirsquidness one of the things on the list to try, we'll hopefully make some progress on this in the next few weeks with stratlan and epic.lite coming up with some time to tinker

**Comment by VibroAxe** [comment]
@shinji257 can you pull the latest steamcache image and then run some steam downloads with --env BEAT_TIME 1m, then upload your /data/logs/access.log for the steam container please

**Comment by shinji257** [comment]
Sorry.  I was looking for this post previously to let you know we had come up with a resolution.

I had it set as primary but the router's own DNS was set as secondary (the upstream for steamcache-dns was set there too).  Seems that for some reason the systems were using the secondary DNS.  I changed our network config to have the router use steamcache-dns as upstream then point steamcache-dns to a public dns from there for its upstream.  After that it worked fine using primarily http sources.

**Comment by VibroAxe** [comment]
glad you got it sorted
