### ISSUE TITLE
Issues with cache domains files

### ISSUE THREAD

**Issue by VibroAxe** [uklans/cache-domains#44]
### Describe the issue you are having
There have been some cache_domains files with incorrect line termination / unprintable characters causing issues with parsing scripts. We need to determine what these are and check more don't get added

See https://github.com/uklans/cache-domains/commit/5e0b1dd992b652cd081e18a3a7204a8dd8710f19 for a fixed file.

**Comment by VibroAxe** [comment]
Possibly be related to #39 but not 100% convinced

**Comment by unspec** [comment]
Resolved in https://github.com/uklans/cache-domains/pull/84 , hopefully.
