### ISSUE TITLE
Please add Star Citizen

### ISSUE THREAD

**Issue by nuhll** [uklans/cache-domains#5]
Hi, since the patches from star citizen are very big, could you please add support for RSI Downloader?

**Comment by VibroAxe** [comment]
Unfortuantely the RSI Downloader uses https downloads instead of http and as such cannot be cached at this time.

**Comment by nuhll** [comment]
Couldnt this be done like on origin with sniproxy?

**Comment by Lepidopterist** [comment]
The reason Origin works with sniproxy is that the actual CDN downloads come over http, and it's just the Origin client *itself* that is retrieved over https.   As all Star Citizen downloads appear to come over https, then sniproxy will only proxy the content, and will be unable to cache it.

**Comment by VibroAxe** [comment]
Unfortuantely at the moment this is an increasing trend in the industry and no-one has yet cracked the "how to cache ssl" issue without distributing root certificates
