### ISSUE TITLE
More host names for PS4

### ISSUE THREAD

**Issue by nexusofdoom** [uklans/cache-domains#53]
### DNS Configuration
```
<!-- Paste either your docker run command for the DNS container OR explain how you have setup DNS zone files etc -->
```

### Sniproxy output
Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
<!-- If you are running sniproxy paste the output to the following command
docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c
-->
```

**Comment by nexusofdoom** [comment]
Ref 
https://github.com/nexusofdoom/lancache-installer/issues/23


I actually spent a wohle day , downloaded over 100 games and deleted them to download them agan and juggled with httpry and nslookup to find all of sony's loadbalancer domains.I think i found most of them, caching now works most of the time, exept the loadbalancer chose to use a level3 server, the server will respond to the ps4 with a direct ip adress, the ip adress will be a different every time you are conected to a level3 server.   local-zone: "pls.patch.station.sony.com." redirect    local-data: "pls.patch.station.sony.com. 30 IN A YOUR-IP-ADDRESS"    local-zone: "playstation.net." transparent    local-zone: "gs2.ww.prod.dl.playstation.net." redirect    local-data: "gs2.ww.prod.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "gs2.sonycoment.loris-e.llnwd.net." redirect    local-data: "gs2.sonycoment.loris-e.llnwd.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "theia.dl.playstation.net." redirect    local-data: "theia.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "tmdb.np.dl.playstation.net." redirect    local-data: "tmdb.np.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "gs-sec.ww.np.dl.playstation.net." redirect    local-data: "gs-sec.ww.np.dl.playstation.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "playstation4.sony.akadns.net." redirect    local-data: "playstation4.sony.akadns.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "gs2-ww-prod.psn.akadns.net." redirect    local-data: "gs2-ww-prod.psn.akadns.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "gs2.ww.prod.dl.playstation.net.edgesuite.net." redirect    local-data: "gs2.ww.prod.dl.playstation.net.edgesuite.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "*.cloudfront.net." redirect    local-data: "*.cloudfront.net. 30 IN A YOUR-IP-ADDRESS"    local-zone: "*.deploy.static.akamaitechnologies.com." redirect    local-data: "*.deploy.static.akamaitechnologies.com. 30 IN A YOUR-IP-ADDRESS"    local-zone: "*.llnw.net." redirect    local-data: "*.llnw.net. 30 IN A YOUR-IP-ADDRESS"
--

**Comment by VibroAxe** [comment]
Thanks for this, some of these domains look to be very useful. However, some of these domains are extremely likely to cause you issues. For example you appear to be caching ALL content on `cloudfront.net` this is very likely to not be compatible with a lancache style caching setup.

Some of the domains might be useful though. This is very similar to #30 so I'm going to close it and add in the domains there for further investigation however it is very unlikely we will add all of them.
