### ISSUE TITLE
Request CDN for Rules of Survival of netease

### ISSUE THREAD

**Issue by nyemenzo** [uklans/cache-domains#58]
can we cache rules of survival updates?

**Comment by unspec** [comment]
If you mean the mobile game, then that's not really something the list is currently geared towards - most LANs are primarily PC based, with some console games as well.

If you mean the steam version then the normal steam domains in the list should work fine (https://store.steampowered.com/app/788260/Rules_Of_Survival/)

**Comment by nyemenzo** [comment]
I own internet cafe and my players dont have money to buy ROS in steam. i downloaded the ROS in their official website https://www.rulesofsurvivalgame.com/.

**Comment by VibroAxe** [comment]
Alas, the download through their website is https encrypted so we are unable to cache this

![image](https://user-images.githubusercontent.com/1069212/52482905-6b87b000-2baa-11e9-85cc-b093d8e834c6.png)
