### ISSUE TITLE
additional domain name for wargaming

### ISSUE THREAD

**Issue by nyemenzo** [uklans/cache-domains#59]
when downloading the game world of warplanes, i notice the log isnt updating. and i found this remote name in my net limiter. the cache when updating the world of tanks is working to me. 

here is the remote name that i got
![image](https://user-images.githubusercontent.com/31677679/52391726-c43b4800-2ad9-11e9-9840-0e0af68a9288.png)

**Comment by VibroAxe** [comment]
@nyemenzo are you by any chance using steamcache-dns?
