### ISSUE TITLE
RIOT not caching

### ISSUE THREAD

**Issue by nyemenzo** [uklans/cache-domains#60]
RIOT not caching because when i check it returns my ISP address not the the riot address or cdn. is it cached content from my ISP thats why i cant cached it anymore. is there a way to cached the content?

**Comment by VibroAxe** [comment]
This could be related to #57 is your domain list up to date on your dns server?

**Comment by VibroAxe** [comment]
Could you also clarify what you mean by "your isp address"

**Comment by nyemenzo** [comment]
i will try to repeat the process using wireshark. because i notice netlimiter give diffirent host.

**Comment by nyemenzo** [comment]
here is the screenshoot i got from wireshark.
![image](https://user-images.githubusercontent.com/31677679/52514252-fddf9080-2c4a-11e9-95b9-9a6b076b34dc.png)

**Comment by nyemenzo** [comment]
notice me senpai.

**Comment by nyemenzo** [comment]
here in asia whe use this https://www.garena.ph/ software to install,update lol. just like steam.

**Comment by nyemenzo** [comment]
@VibroAxe
