### ISSUE TITLE
Can you add Garena?

### ISSUE THREAD

**Issue by nyemenzo** [uklans/cache-domains#65]
Garena is like steam client. they work as mediator to other games. can you add it in your cache domains specifically in Philippine Region that can be change in Garena Settings. Thank you.

**Comment by unspec** [comment]
Hi,

We're happy to consider new gaming services to add to the domains list, but we don't really have the capability to work out the hostnames for this one on your behalf (we don't have any contributors in the philippines and dont get much use of Garena).

If yourself or anyone else is able to submit a PR with the the hostnames, we're happy to review it.

Thanks,
