### ISSUE TITLE
Riot Caching but all miss

### ISSUE THREAD

**Issue by nyemenzo** [uklans/cache-domains#66]
### Describe the issue you are having
after i updated riot.txt with this lolph.cdn.gpipe.garenanow.com it is now caching files. but every time i download LOL in garena its MISS with no HIT

### Describe your setup?
i fork steamcache-dns and change bootstrap.sh with my edited repository that i fork from uklan to change some domains.

### Are you running sniproxy
YES

### DNS Configuration
```
sudo docker run --restart unless-stopped --name steamcache-dns -d -p 192.168.8.10:53:53/udp e- RIOTCACHE_IP=192.168.8.12 -e UPSTREAM_DNS=8.8.8.8.8 dropme123/mycache-domains:latest
```

### Sniproxy output
sorry im newbies in this this, is just i get.
i see bunch of this out put and i will copy the last one
1 2019-02-12 23:18:02 192.168.8.8:63119 -> 0.0.0.0:443 -> NONE [
25 edgecast.cdn.steampipe.steamcontent.com
1 level13.cdn.steampipe.steamcontent.com
153 steamcdn-a.akamaihd.net
21 wgus-wotasia.wargaming.net

**Comment by nyemenzo** [comment]
when i open wire shark this is i got. thank you
[
![cache](https://user-images.githubusercontent.com/31677679/52676164-237adb80-2f64-11e9-9229-0b2cb2a28a71.png)
](url)

**Comment by VibroAxe** [comment]
This is not an issue with the cache domains project.
