### ISSUE TITLE
Add Nintendo Wii U eShop addresses (3DS eShop too, if possible?)

### ISSUE THREAD

**Issue by some-username-here1** [uklans/cache-domains#68]
Add addresses for the Wii U eShop? (also maybe 3DS eShop, too)
I was hoping that the current `nintendo.txt` config had addresses that gave steamcache-dns the ability to cache the files, but tailing the log file in my `nintendo` directory says otherwise...

**Comment by Lepidopterist** [comment]
Excellent idea.  Please raise a PR once you have determined which hosts are applicable.

**Comment by some-username-here1** [comment]
How do I monitor the incoming/outgoing addresses for my Wii U?
Since this would be my first time to do such a thing

**Comment by some-username-here1** [comment]
Nevermind, I'm currently looking through the incoming traffic by forcing it through my cache server as a DNS, will probably take a while to look through

**Comment by some-username-here1** [comment]
I'm back, and most likely with a list of all the addresses that my Wii U contacted as it was download DLC for Mario Kart 8:

```
0xbfd7 A ccs.cdn.wup.shop.nintendo.net

0x7a8f A ccs.cdn.wup.shop.nintendo.net OPT

0x39e2 NS <root> OPT

0x39e2 NS <root> NS i.root-servers.net NS j.root-servers.net NS k.root-servers.net NS l.root-servers.net NS m.root-servers.net NS a.root-servers.net NS b.root-servers.net NS c.root-servers.net NS d.root-servers.net NS e.root-servers.net NS f.root-servers.net NS g.root-servers.net

0x7a8f A ccs.cdn.wup.shop.nintendo.net CNAME css.cdn.wup.shop.nintendo.net.edgesuite.net CNAME a1702.g.akamai.net 23.63.75.72 A 23.63.75.67 OPT

0x53d6 A a1702.g.akamai.net OPT

-----------------------------------------------------------------------

0x9158 A ccs.cdn.wup.shop.nintendo.net

0x5f02 A ccs.cdn.wup.shop.nintendo.net OPT

0xf4a0 NS <root> NPT

0xf4a0 NS <root> NS m.root-servers.net NS a.root-servers.net NS b.root-servers.net NS c.root-servers.net NS d.root-servers.net NS e.root-servers.net NS f.root-servers.net NS g.root-servers.net NS h.root-servers.net NS i.root-servers.net NS j.root-servers.net NS k.root-servers.net NS l.root-servers.net RRSIG OPT

0x5f02 A ccs.cdn.wup.shop.nintendo.net CNAME ccs.cdn.wup.shop.nintendo.net.edgesuite.net CNAME a1702.g.akamai A 23.62.60.178 A 23.62.60.177 OPT

0x1aa9 A a1702.g.akamai.net A 23.62.60.177 A 23.62.60.178 OPT

0x9158 A ccs.cdn.wup.shop.nintendo.net CNAME ccs.cdn.wup.shop.nintendo.net.edgesuite.net CNAME a1702.g.akamai.net A 23.62.60.178 A 23.62.60.177
```

With "0xXXXX" being after "Standard query" in the Info section on Wireshark, and the list of possbile addresses are `ccs.cdn.wup.shop.nintendo.net`, `ccs.cdn.wup.shop.nintendo.net.edgesuite.net`, `23.62.60.177`, `23.62.60.178`, `a1702.g.akamai.net`, and `(a-m).root-servers.net`

Also, are Transaction IDs needed, or not really?

**Comment by some-username-here1** [comment]
I found more addresses while downloading a few games, though there could still be more
```
a1702.g.akamai.net
e6022.d.akamaiedge.net
*.deploy.static.akamaitechnologies.com
*.us-west-2.compute.amazonaws.com
ccs.cdn.wup.shop.nintendo.net
ccs.cdn.wup.shop.nintendo.net.edgesuite.net
geisha-wup.cdn.nintendo.net
geisha-wup.cdn.nintendo.net.edgekey.net
ninja.wup.shop.nintendo.net
ninja.wup.eshop.nintendo.net
tagaya.wup.shop.nintendo.net
tagaya.wup.eshop.nintendo.net
a.root-servers.net
b.root-servers.net
c.root-servers.net
d.root-servers.net
e.root-servers.net
f.root-servers.net
g.root-servers.net
h.root-servers.net
i.root-servers.net
j.root-servers.net
k.root-servers.net
l.root-servers.net
m.root-servers.net
```

**Comment by some-username-here1** [comment]
oh, I noticed that `*.deploy.static.akamaitechnologies.com` was mentioned in #30, so that could be a problem

**Comment by VibroAxe** [comment]
@some-username-here1 Are these urls definitely using http or are they using https?

**Comment by some-username-here1** [comment]
Let me check, as I saved a file of the packet capture from Wireshark. I've saved a couple of multiple downloads, too

Also where do I go check to see if it gone over `http` or `https`?

**Comment by VibroAxe** [comment]
Merged
