### ISSUE TITLE
New section in README.md for manual web addresses implementation?

### ISSUE THREAD

**Issue by some-username-here1** [uklans/cache-domains#75]
Can there be a new section in `README.md` for a manual setup, and information on how to manually add web addresses yourself, to the DNS, for when you want to test which addresses can work for caching and which doesn't? and in terms of private testing with forked repositories / branches, so that it can be tested before making an Issue or Pull Request

As this can be really helpful for newcomers and those that want to help contribute to the project.

Also maybe mentioning where the files are located, and on how to create new containers with manually added addresses, or editing already-created services that you can add additional web addresses

**Comment by VibroAxe** [comment]
Forking the repo is the route forward on this. Both lancache-dns and lancache-monolithic support using your own repo instead of the cache domains master.

This repo is for collating the domain lists only
