### ISSUE TITLE
Cache for Minecraft Launcher (clarification?)

### ISSUE THREAD

**Issue by some-username-here1** [uklans/cache-domains#78]
Since the new launcher forces **https** when it comes to downloading within the launcher, as I've tested a couple of times (before PR #72 was reverted), being this one (as a `exe` instead of a `jar` file):
![Minecraft Launcher v2.1.2468](https://user-images.githubusercontent.com/34193156/52955138-d1113480-3340-11e9-9bf9-8cb148e09199.png)

The solution for getting the cache to work is using the old (legacy?) version of the launcher, being this one (as it doesn't force https, I think):
![Minecraft Launcher v1.6.84-j](https://user-images.githubusercontent.com/34193156/52955233-0158d300-3341-11e9-97c1-928362485655.png)

**Comment by VibroAxe** [comment]
Hi @some-username-here1 
We've given this some though and given the relatively small file size of minecraft downloads and the likely hood of people running the newer launch I don't think it's sensible to add the minecraft domains back in. From experience they are more likely to create confusion with the cache "not working" than the benefit gained for a few network users still using the old launcher (which I don't believe is officially supported anymore anyway)

We are working on the ability to switch the dns image to use your own repo which would enable you to add your own domains to the list without us, but thats not quite finished yet. Watch https://github.com/steamcache/steamcache-dns/issues/68 for details
