### ISSUE TITLE
Feedback: Add round-robin DNS support to allow multiple IPs for services

### ISSUE THREAD

**Issue by maxxoverclocker** [uklans/cache-domains#83]
### Describe the issue you are having
Currently create-unbound.sh only supports a single IP address for each service. steamcache/monolithic supports multiple IPs for each domain to allow for increased performance. A simple addition of the following to create-unbound.sh allows for multiple IPs to be defined in the config.json separated by spaces:
Before:
`echo "  local-data: \"${parsed} 30 IN A ${cacheip}\"" >> $outputfile`
After:
`for ip in $cacheip; do
    echo "local-data: \"${parsed} 30 IN A ${ip}\""
done | sort -R  >> $outputfile`

**Comment by VibroAxe** [comment]
Resolved in #92
