### ISSUE TITLE
path support in URLs?

### ISSUE THREAD

**Issue by some-username-here1** [uklans/cache-domains#85]
Hello!
I would like to know if paths in a URL is supported, so that I could cache from `mirror.example.com/linux/flavor` instead of `mirror.example.com`, as I'm creating a new branch, being [linux](https://github.com/some-username-here1/cache-domains/tree/linux), in my own fork of this repository.

If not, can this be made into a feature in the future, when possible?

**Comment by Crabbey** [comment]
Hi,

We have no intention at the moment to add paths, since it is out of scope for this project, and it's intended use cases.

**Comment by unspec** [comment]
As @Crabbey says, URL level caching is not really required for this project. It's also worth noting that this is designed as a list of hostnames for DNS overrides or similar, which is an all or nothing approach really - in this example you either override the IP for the mirror.example.com hostname to a local IP or you don't.

You could potentially look at adding logic on your cache server to cache certain paths/files and pass the rest straight through from the upstream, but its not something that this domains list can really assist with.
