### ISSUE TITLE
Additional WSUS domain?

### ISSUE THREAD

**Issue by nightah** [uklans/cache-domains#99]
### Describe the issue you are having
Not so much an issue but I'm noticing both in my cacheserver logs and my ELK stack reporting the following domain: `amupdatedl.microsoft.com`.

With some further investigation it looks like it's my Windows 2019 Server going out for updates, the odd thing is that hostname isn't being redirected to the cacheserver yet it still shows up in the logs per the below snippet:

```
[amupdatedl.microsoft.com] 10.10.10.100 / - - - [03/Jul/2019:20:07:19 +1000] "GET /server/amupdate/amd64/Microsoft/Package/1907030004/mpasdlta.vdm.cab HTTP/1.1" 302 0 "-" "Microsoft BITS/7.8" "MISS" "amupdatedl.microsoft.com" "-"
[amupdatedl.microsoft.com] 10.10.10.100 / - - - [03/Jul/2019:20:07:22 +1000] "GET /server/amupdate/amd64/Microsoft/Package/1907030004/mpasdlta.vdm.cab HTTP/1.1" 302 0 "-" "Microsoft BITS/7.8" "MISS" "amupdatedl.microsoft.com" "-"
[amupdatedl.microsoft.com] 10.10.10.100 / - - - [03/Jul/2019:20:07:31 +1000] "GET /server/amupdate/amd64/Microsoft/Package/1907030004/mpavbase.vdm.cab HTTP/1.1" 302 0 "-" "Microsoft BITS/7.8" "MISS" "amupdatedl.microsoft.com" "-"
[amupdatedl.microsoft.com] 10.10.10.100 / - - - [03/Jul/2019:20:07:33 +1000] "GET /server/amupdate/amd64/Microsoft/Package/1907030004/mpavbase.vdm.cab HTTP/1.1" 302 0 "-" "Microsoft BITS/7.8" "MISS" "amupdatedl.microsoft.com" "-"
```

Should I PR the domain at least so it's classified in the wsus bucket?

### Describe your setup?
I'm using dnsmasq along with the monolithic container.

### Are you running sniproxy

Yes

### DNS Configuration
I've used the dnsmasq generate shell script to configure the required domains.

### Sniproxy output
<!-- Please paste the output from `docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c` below
```
<!-- If you are running sniproxy paste the output to the following command
docker logs <sniproxy container name/id> | sed 's/.*\:443 \[//;s/\].*//' | sort | uniq -c
-->
```
1 2019-06-10 01:25:18 10.10.0.1:50054 -> 172.18.0.37:443 -> NONE [
1 2019-06-10 08:39:50 10.10.0.1:53009 -> 172.18.0.37:443 -> NONE [
1 2019-06-19 04:09:35 10.10.10.100:49757 -> 172.18.0.32:443 -> NONE [
1 2019-06-19 04:09:35 10.10.10.100:49758 -> 172.18.0.32:443 -> NONE [
1 2019-06-19 04:09:35 10.10.10.100:49759 -> 172.18.0.32:443 -> NONE [
1 2019-06-19 04:09:35 10.10.10.100:49760 -> 172.18.0.32:443 -> NONE [
1 2019-06-19 04:09:35 10.10.10.100:49761 -> 172.18.0.32:443 -> NONE [
1 2019-06-19 04:09:35 10.10.10.100:49762 -> 172.18.0.32:443 -> NONE [
1 2019-06-19 04:09:35 10.10.10.100:49763 -> 172.18.0.32:443 -> NONE [
1 2019-06-19 04:09:35 10.10.10.100:49764 -> 172.18.0.32:443 -> NONE [
13 array602-prod.do.dsp.mp.microsoft.com
20 array607-prod.do.dsp.mp.microsoft.com
30 array614-prod.do.dsp.mp.microsoft.com
1 cm01-hkg.cm.steampowered.com
1 cm01-lax.cm.steampowered.com
1 cm-01-sea1.cm.steampowered.com
3 cm02-hkg.cm.steampowered.com
2 cm02-lax.cm.steampowered.com
3 cm-02-okc1.cm.steampowered.com
2 cm02-ord.cm.steampowered.com
1 cm-02-sea1.cm.steampowered.com
3 cm03-lax.cm.steampowered.com
1 cm04-ord.cm.steampowered.com
2 cm1-sgp1.cm.steampowered.com
4 cm1-syd1.cm.steampowered.com
4 cm1-tyo1.cm.steampowered.com
3 cm2-tyo1.cm.steampowered.com
1 cm3-hkg1.cm.steampowered.com
3 cm3-iad1.cm.steampowered.com
1 cm3-sgp1.cm.steampowered.com
2 cm4-iad1.cm.steampowered.com
243 cp601-prod.do.dsp.mp.microsoft.com
6 disc601-prod.do.dsp.mp.microsoft.com
3 fe2cr.update.microsoft.com
80 fe2.update.microsoft.com
42 geo-prod.do.dsp.mp.microsoft.com
47 kv601-prod.do.dsp.mp.microsoft.com
112 nydus.battle.net
7 origin-a.akamaihd.net
226 river.data.ea.com
6 slscr.update.microsoft.com
338 sls.update.microsoft.com
18 static2.cdn.ubi.com
```

**Comment by unspec** [comment]
amupdatedl.microsoft.com appears to be a CNAME for amupdatedl.microsoft.com.edgesuite.net - which does match the "*.microsoft.com.edgesuite.net" entry in the WSUS domains file, so i suspect thats how the traffic ended up hitting your cache.

As it appears to be a direct CNAME to a hostname we are already caching with no reported problems, I'd say there is no harm in adding that URL directly to the domains file for reporting purposes if nothing else.

**Comment by unspec** [comment]
Thanks @nightah
